# Generated by Django 4.2.6 on 2023-12-21 06:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chief_ID', models.CharField(max_length=100)),
                ('Chief_Surname', models.CharField(max_length=100)),
                ('Chief_FirstName', models.CharField(max_length=100)),
                ('Chief_Location', models.CharField(max_length=100)),
                ('Chief_Image', models.ImageField(upload_to='media')),
                ('Chief_Gender', models.CharField(max_length=100)),
                ('Chief_Marital_Status', models.CharField(max_length=100)),
                ('Chief_Contact', models.CharField(max_length=100)),
                ('Chief_Ghana_Card_Id', models.CharField(max_length=100)),
                ('Chief_Region', models.CharField(max_length=100)),
                ('Chief_District', models.CharField(max_length=100)),
                ('Chief_Rank_of_Chieftaincy', models.CharField(max_length=100)),
                ('Chief_Year_of_Enstoolment', models.CharField(max_length=100)),
                ('Chief_Year_of_Chieftancy_End', models.CharField(max_length=100)),
                ('Chief_Qualification', models.CharField(max_length=100)),
                ('Chief_EmailField', models.EmailField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelOwnerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parcel_Owner_ID', models.CharField(max_length=100, unique=True)),
                ('Parcel_Owner_Surname', models.CharField(max_length=100)),
                ('Parcel_Owner_FirstName', models.CharField(max_length=100)),
                ('Parcel_Owner_Location', models.CharField(max_length=100)),
                ('Parcel_Owner_Image', models.ImageField(upload_to='media')),
                ('Parcel_Owner_Gender', models.CharField(max_length=100)),
                ('Parcel_Owner_Age', models.PositiveIntegerField()),
                ('Parcel_Owner_Marital_Status', models.CharField(max_length=100)),
                ('Parcel_Owner_Next_of_Kin', models.CharField(max_length=100)),
                ('Parcel_Owner_Contact', models.CharField(max_length=100)),
                ('Parcel_Owner_Next_of_Kin_Contact', models.CharField(max_length=100)),
                ('Parcel_Owner_Ghana_Card_Id', models.CharField(max_length=100)),
                ('Parcel_Owner_Qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('Parcel_Owner_EmailField', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolygonModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Survey_Licence_Number', models.CharField(max_length=100)),
                ('Survey_Surname', models.CharField(max_length=100)),
                ('Survey_FirstName', models.CharField(max_length=100)),
                ('Survey_Location', models.CharField(max_length=100)),
                ('Survey_Image', models.ImageField(upload_to='media')),
                ('Survey_Gender', models.CharField(max_length=100)),
                ('Survey_Age', models.PositiveIntegerField()),
                ('Survey_Marital_Status', models.CharField(max_length=100)),
                ('Survey_Contact', models.CharField(max_length=100)),
                ('Survey_Ghana_Card_Id', models.CharField(max_length=100)),
                ('Survey_Qualification', models.CharField(max_length=100)),
                ('Survey_Year_Of_Completions', models.CharField(max_length=100)),
                ('Survey_Institution_of_Completion', models.CharField(max_length=100)),
                ('Survey_Professional_Body', models.CharField(max_length=100)),
                ('Survey_EmailField', models.EmailField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parcel_ID', models.PositiveIntegerField()),
                ('Parcel_District', models.CharField(max_length=100)),
                ('Parcel_Region', models.CharField(max_length=100)),
                ('parcel_Locality', models.CharField(max_length=100)),
                ('Parcel_Status', models.CharField(max_length=100)),
                ('Parcel_land_interest_type', models.CharField(max_length=100)),
                ('Parcel_Boundary', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='LandApp.polygonmodels')),
                ('Parcel_Chief_Involved', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='LandApp.chiefdetails')),
                ('Parcel_Owner', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='LandApp.parcelownerdetails', to_field='Parcel_Owner_ID')),
                ('Parcel_surveyor_who_demarcated', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='LandApp.surveyordetails')),
            ],
        ),
    ]
