# Generated by Django 4.2.6 on 2023-12-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceldetails',
            name='Parcel_ID',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
