# Generated by Django 4.2.6 on 2023-12-22 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LandApp', '0002_alter_parceldetails_parcel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceldetails',
            name='Parcel_Owner',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='LandApp.parcelownerdetails'),
        ),
    ]
