# Generated by Django 4.2.6 on 2023-12-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandApp', '0004_alter_parceldetails_parcel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceldetails',
            name='Eastings',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='parceldetails',
            name='Latitude',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='parceldetails',
            name='Longitude',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='parceldetails',
            name='Northings',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='chiefdetails',
            name='Chief_Image',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='parcelownerdetails',
            name='Parcel_Owner_Image',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='surveyordetails',
            name='Survey_Image',
            field=models.BinaryField(),
        ),
    ]
