# Generated by Django 4.2.6 on 2023-12-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandApp', '0005_parceldetails_eastings_parceldetails_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefdetails',
            name='Chief_Image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='parcelownerdetails',
            name='Parcel_Owner_Image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='surveyordetails',
            name='Survey_Image',
            field=models.TextField(),
        ),
    ]
