# Generated by Django 4.2.6 on 2023-12-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandApp', '0011_alter_chiefdetails_chief_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chiefdetails',
            name='Chief_Image',
        ),
        migrations.RemoveField(
            model_name='parcelownerdetails',
            name='Parcel_Owner_Image',
        ),
        migrations.RemoveField(
            model_name='surveyordetails',
            name='Survey_Image',
        ),
    ]
