# Generated by Django 4.2.6 on 2023-12-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandApp', '0013_remove_parceldetails_eastings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiefdetails',
            name='Chief_Image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='parcelownerdetails',
            name='Parcel_Owner_Image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='surveyordetails',
            name='Survey_Image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='surveyordetails',
            name='Survey_Gender',
            field=models.CharField(),
        ),
    ]
