# Generated by Django 4.2.6 on 2023-12-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandApp', '0014_chiefdetails_chief_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceldetails',
            name='Eastings',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='parceldetails',
            name='Latitude',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='parceldetails',
            name='Longitude',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='parceldetails',
            name='Northings',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
