# Generated by Django 4.2.6 on 2023-12-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandApp', '0015_parceldetails_eastings_parceldetails_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceldetails',
            name='Eastings',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parceldetails',
            name='Latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parceldetails',
            name='Longitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parceldetails',
            name='Northings',
            field=models.CharField(max_length=100),
        ),
    ]
