# Generated by Django 4.2.6 on 2023-12-25 07:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandApp', '0017_alter_parceldetails_eastings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceldetails',
            name='Eastings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='parceldetails',
            name='Latitude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='parceldetails',
            name='Longitude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='parceldetails',
            name='Northings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
    ]
